import { StackPreset, StackType } from "./types";

export const STACK_PRESETS: Record<StackType, StackPreset> = {
  ai: {
    id: "ai",
    label: "Artificial Intelligence",
    builderType: "Model Whisperer",
    principle: "Build. Learn. Repeat.",
    tagline: "Neural Architect & Intelligence Craftsman",
    accentColor: "#00F0FF",
    badgeBg: "bg-cyan-950/80",
    badgeText: "text-cyan-300 border-cyan-500/40",
    borderColor: "border-cyan-500/50",
    glowColor: "rgba(0, 240, 255, 0.25)",
    patternType: "neural",
  },
  frontend: {
    id: "frontend",
    label: "Frontend & Interface",
    builderType: "Experience Designer",
    principle: "Everyone builds. No watching.",
    tagline: "Pixel Perfectionist & Interaction Specialist",
    accentColor: "#FF007F",
    badgeBg: "bg-pink-950/80",
    badgeText: "text-pink-300 border-pink-500/40",
    borderColor: "border-pink-500/50",
    glowColor: "rgba(255, 0, 127, 0.25)",
    patternType: "grid",
  },
  backend: {
    id: "backend",
    label: "Backend & Systems",
    builderType: "Systems Builder",
    principle: "Ship before perfect.",
    tagline: "Distributed Systems & High-Throughput Architect",
    accentColor: "#FACC15",
    badgeBg: "bg-yellow-950/80",
    badgeText: "text-yellow-300 border-yellow-500/40",
    borderColor: "border-yellow-500/50",
    glowColor: "rgba(250, 204, 21, 0.25)",
    patternType: "server",
  },
  cybersecurity: {
    id: "cybersecurity",
    label: "Cybersecurity & Defense",
    builderType: "Digital Sentinel",
    principle: "Quality is set at the door.",
    tagline: "Cryptographic Guardian & Protocol Shield",
    accentColor: "#FF3344",
    badgeBg: "bg-red-950/80",
    badgeText: "text-red-300 border-red-500/40",
    borderColor: "border-red-500/50",
    glowColor: "rgba(255, 51, 68, 0.25)",
    patternType: "cyber",
  },
  cloud: {
    id: "cloud",
    label: "Cloud & Infrastructure",
    builderType: "Infrastructure Explorer",
    principle: "Build things that matter.",
    tagline: "Orchestration Master & Resilience Lead",
    accentColor: "#10B981",
    badgeBg: "bg-emerald-950/80",
    badgeText: "text-emerald-300 border-emerald-500/40",
    borderColor: "border-emerald-500/50",
    glowColor: "rgba(16, 185, 129, 0.25)",
    patternType: "cloud",
  },
  blockchain: {
    id: "blockchain",
    label: "Web3 & Blockchain",
    builderType: "Protocol Pioneer",
    principle: "Keep showing up.",
    tagline: "Decentralized State & Smart Contract Engineer",
    accentColor: "#F59E0B",
    badgeBg: "bg-amber-950/80",
    badgeText: "text-amber-300 border-amber-500/40",
    borderColor: "border-amber-500/50",
    glowColor: "rgba(245, 158, 11, 0.25)",
    patternType: "mesh",
  },
};

export const DEFAULT_STACK: StackType = "frontend";
